general {
    background = rgb(14171d)
    foreground = rgb(d0d7de)
    accent = rgb(88a4c2)
    selection_background = rgb(282e3b)
    selection_foreground = rgb(f0f4f8)
    rounding = 0
}

ui {
    window_size = 620 400
}

finders {
    desktop_icons = true
    desktop_terminal = kitty
}
